name: 'passing values between steps'
on:
  workflow_dispatch:
jobs:
  passing-values-between-steps:
    runs-on: ubuntu-latest
    steps:
      - name: set the value using Env vars
        run: |
          echo "variableName=this-is-a-value" >> $GITHUB_ENV
      - name: create-variables
        id: var_source_step
        run: |
          echo "::set-ouput name=var1_name::Techschool"
          echo "::set-output name=var2_name::$(date +%Y-%m-%d)"
      - name: get-variable-value
        run: |
          echo "printing values from previous steps"
          echo "var1_name is ${{ steps.var_source_step.outputs.var1_name }}"
          echo "var2_name is ${{ steps.var_source_step.outputs.var2_name }}"
          echo "variableName is $variableName"
          
        